### ISSUE TITLE
Electrode location for AF3 and AF4 in 1010 format

### ISSUE THREAD

**Issue by Aceticia** [sappelhoff/eeg_positions#1]
Hello, this project helps me a lot in my research. However, in one of the dataset I collected, it uses AF3 and AF4 electrode in 1010 format, which is not included in your code. Is it possible to add these two to the collection? Thanks.

ref: https://www.acns.org/UserFiles/file/Guideline2-GuidelinesforStandardElectrodePositionNomenclature_v1.pdf

**Comment by sappelhoff** [comment]
Hi @Aceticia I am happy that this project is useful for you. If you have a list of channel names that you need coordinates for, you can simply pick the 10-05 coordinates (see [here](https://github.com/sappelhoff/eeg_positions/blob/master/data/standard_1005.tsv)) and select only the rows corresponding to the channel names you need.

10-05 includes coordinates for AF3 and AF4. See row 8 and 10 in this Screenshot:

![grafik](https://user-images.githubusercontent.com/9084751/102549220-09f4ce80-40bc-11eb-8115-4437efbe56b8.png)

**Comment by Aceticia** [comment]
You are right. Thank you for the help.
