### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by larsoner** [sappelhoff/eeg_positions#26]
Any chance for a quick release to fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/26005/workflows/81bab303-2b79-47e3-9261-526713af9874/jobs/70185 ?

**Comment by sappelhoff** [comment]
Yes, will do asap :)

**Comment by sappelhoff** [comment]
https://pypi.org/project/eeg-positions/2.1.2/

conda-forge should follow soon
