### ISSUE TITLE
The difference between Fpz-T8-Oz-T7 and Nz-T10-Iz-T9

### ISSUE THREAD

**Issue by zhaoyanxi** [sappelhoff/eeg_positions#5]
Hi，this repo works for me. May I know the difference between the two modes (Fpz-T8-Oz-T7 and Nz-T10-Iz-T9)?

**Comment by sappelhoff** [comment]
Hi @zhaoyanxi, you can read more about that here: https://stefanappelhoff.com/eeg_positions/generated/eeg_positions.get_elec_coords.html#eeg_positions.get_elec_coords under the `equator_contour` parameter:

> Control which contour line of electrodes should be at the equator of the sphere. Both permissible options ("Nz-T10-Iz-T9" or "Fpz-T8-Oz-T7") are reasonable assumptions. Selecting "Nz-T10-Iz-T9" is recommended, because the electrodes Nz, T9, and T10 correspond to the anatomical landmarks NAS, LPA, and RPA in our spherical head model (see Notes section). Thus, the anatomical landmarks lie on the equator, and all electrodes are drawn inside a circule head shape when projecting to 2D. The option to select "Fpz-T8-Oz-T7" is provided (but not recommended), because this contour line corresponds to where the head circumference would be measured for real humans. However, when selecting "Fpz-T8-Oz-T7" as the equator, several electrodes may be drawn outside a circular head shape when projecting to 2D. Defaults to "Nz-T10-Iz-T9".

Basically: We compute the electrode positions on a sphere according to the 10-20 (or by logical extension 10-10, or 10-05) system. For that we have to make some assumptions: such as which electrodes lie on the equator of our sphere. Practically it makes only little difference, and I recommend the default (`"Nz-T10-Iz-T9"`).
