### ISSUE TITLE
Increase head plot size

### ISSUE THREAD

**Issue by cbrnr** [sappelhoff/eeg_positions#6]
Hey @sappelhoff, I am starting to use your package to create nice visualizations for my studies. I hope you are aware that this means new issues and PRs will be incoming 😄!

First, I think the default head size when plotting coordinates with `plot_coords()` is rather small:

```python
fig, ax = plot_coords(coords)
```

![before](https://user-images.githubusercontent.com/4377312/173547233-a696315d-398d-4da4-8900-362a597678f4.png)

I can increase/maximize it afterwards by:

```python
ax.set_axis_off()
fig.set_tight_layout(True)
ax.set_xlim([-1.1, 1.1])
ax.set_ylim([-1.1, 1.1])
```
![after](https://user-images.githubusercontent.com/4377312/173547349-a3a71d38-c777-4543-b4a0-4232bb2ffe81.png)

Would you be OK with including this by default? If yes, where would you prefer to do it?

**Comment by sappelhoff** [comment]
Hi -- yes, I am happy to receive bug reports and review PRs :-)

you can just send a PR with your improvements and we can iterate (if needed) in a PR, the docs build will help us judge whether the changes are an improvement or not.

**Comment by cbrnr** [comment]
Are you OK with removing the x- and y-axes? Or do you want a parameter?

**Comment by sappelhoff** [comment]
let's have a parameter
